#region 程序集 Microsoft.VisualStudio.Interop, Version=17.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
// C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\PublicAssemblies\Microsoft.VisualStudio.Interop.dll
// Decompiled with ICSharpCode.Decompiler 7.1.0.6543
#endregion

namespace Microsoft.VisualStudio.Shell.Interop
{
    public enum __VSHPROPID
    {
        VSHPROPID_NIL = -1,
        VSHPROPID_LAST = -1000,
        VSHPROPID_Parent = -1000,
        VSHPROPID_FirstChild = -1001,
        VSHPROPID_NextSibling = -1002,
        VSHPROPID_Root = -1003,
        VSHPROPID_TypeGuid = -1004,
        VSHPROPID_SaveName = -2002,
        VSHPROPID_Caption = -2003,
        VSHPROPID_IconImgList = -2004,
        VSHPROPID_IconIndex = -2005,
        VSHPROPID_Expandable = -2006,
        VSHPROPID_ExpandByDefault = -2011,
        VSHPROPID_ProjectName = -2012,
        VSHPROPID_Name = -2012,
        VSHPROPID_IconHandle = -2013,
        VSHPROPID_OpenFolderIconHandle = -2014,
        VSHPROPID_OpenFolderIconIndex = -2015,
        VSHPROPID_CmdUIGuid = -2016,
        VSHPROPID_SelContainer = -2017,
        VSHPROPID_BrowseObject = -2018,
        VSHPROPID_AltHierarchy = -2019,
        VSHPROPID_AltItemid = -2020,
        VSHPROPID_ProjectDir = -2021,
        VSHPROPID_SortPriority = -2022,
        VSHPROPID_UserContext = -2023,
        VSHPROPID_EditLabel = -2026,
        VSHPROPID_ExtObject = -2027,
        VSHPROPID_ExtSelectedItem = -2028,
        VSHPROPID_StateIconIndex = -2029,
        VSHPROPID_ProjectType = -2030,
        VSHPROPID_TypeName = -2030,
        VSHPROPID_ReloadableProjectFile = -2031,
        VSHPROPID_HandlesOwnReload = -2031,
        VSHPROPID_ParentHierarchy = -2032,
        VSHPROPID_ParentHierarchyItemid = -2033,
        VSHPROPID_ItemDocCookie = -2034,
        VSHPROPID_Expanded = -2035,
        VSHPROPID_ConfigurationProvider = -2036,
        VSHPROPID_ImplantHierarchy = -2037,
        VSHPROPID_OwnerKey = -2038,
        VSHPROPID_StartupServices = -2040,
        VSHPROPID_FirstVisibleChild = -2041,
        VSHPROPID_NextVisibleSibling = -2042,
        VSHPROPID_IsHiddenItem = -2043,
        VSHPROPID_IsNonMemberItem = -2044,
        VSHPROPID_IsNonLocalStorage = -2045,
        VSHPROPID_StorageType = -2046,
        VSHPROPID_ItemSubType = -2047,
        VSHPROPID_OverlayIconIndex = -2048,
        VSHPROPID_DefaultNamespace = -2049,
        VSHPROPID_IsNonSearchable = -2051,
        VSHPROPID_IsFindInFilesForegroundOnly = -2052,
        VSHPROPID_CanBuildFromMemory = -2053,
        VSHPROPID_PreferredLanguageSID = -2054,
        VSHPROPID_ShowProjInSolutionPage = -2055,
        VSHPROPID_AllowEditInRunMode = -2056,
        VSHPROPID_IsNewUnsavedItem = -2057,
        VSHPROPID_ShowOnlyItemCaption = -2058,
        VSHPROPID_ProjectIDGuid = -2059,
        VSHPROPID_DesignerVariableNaming = -2060,
        VSHPROPID_DesignerFunctionVisibility = -2061,
        VSHPROPID_HasEnumerationSideEffects = -2062,
        VSHPROPID_DefaultEnableBuildProjectCfg = -2063,
        VSHPROPID_DefaultEnableDeployProjectCfg = -2064,
        VSHPROPID_FIRST = -2064
    }
}